name: Verify and tests
on: 
    push:
        branches:
            - main
            - develop
        tags:

    pull_request:

jobs:
    test:
        strategy:
            matrix:
                py:
                    - "3.8"
                    - "3.9"
                    - "3.10"
                    - "pypy-3.8"
                os:
                    - "ubuntu-20.04"
                architecture:
                    - x64
                include:
                    - os: "ubuntu-20.04"
                      pytest-args: "--cov"
                      # skip coverage on pypy3
                    - os: "ubuntu-20.04"
                      py: "pypy-3.8"
                      pytest-args: ""
                # TODO: ARM based

        name: "Python ${{ matrix.py }} on ${{ matrix.os }}"
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - name: setup python ${{ matrix.py }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.py }}
            - run: pip install tox
            - name: run tox check
              run: tox -e py -- ${{ matrix.pytest-args }}
    coverage:
        runs-on: ubuntu-20.04
        name: Measuring coverage
        steps:
            - uses: actions/checkout@v3
            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: 3.8
                architecture: x64
            - run: pip install tox
            - run: tox -e py38-cover,coverage
    lint:
        runs-on: ubuntu-20.04
        name: Linter
        steps:
            - uses: actions/checkout@v3
            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: 3.8
                architecture: x64
            - run: pip install tox
            - run: tox -e lint
           
